language: node_js
node_js:
- '6.9'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script: yarn run lint && yarn run test
notifications:
  slack: craft-ai:ZNnQErHJhw40oKmphy3fNGza
  email:
  - ops@craft.ai
